sudo: false

language: php

php:
  - 7
  - 7.1

env:
  - COMPOSER_FLAGS=--prefer-lowest

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction --prefer-source --prefer-stable --prefer-lowest

script:
    - vendor/bin/phpunit