sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  - COMPOSER_FLAGS=--prefer-lowest

matrix:
  exclude:
    - php: hhvm
      env: COMPOSER_FLAGS=--prefer-lowest
  include:
    - php: hhvm
      env: COMPOSER_FLAGS=

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction --prefer-source --prefer-stable ${COMPOSER_FLAGS}

script:
    - vendor/bin/phpunit